# Configuration file for Uruguay Climate Change project

# Data paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  external_dir: "data/external"
  interim_dir: "data/interim"

# Model parameters
model:
  random_state: 42
  test_size: 0.2
  validation_size: 0.1

# Feature engineering
features:
  target_column: "temperature"  # Change based on your target variable
  date_column: "date"

# Training parameters
training:
  n_estimators: 100
  max_depth: 10
  learning_rate: 0.01

# Visualization
visualization:
  figures_dir: "reports/figures"
  dpi: 300
  figsize: [12, 6]

# Logging
logging:
  level: "INFO"
  log_file: "logs/training.log"
